### PR TITLE
update from city to state

### PR DESCRIPTION
**Pull request by dforz**
I will change the airtable field when this is merged

### CODE REVIEW

**Comment by HarryAKA** [comment]
i'd prefer a more generic field title than city or state, how about locale?

**Comment by dforz** [comment]
@HarryAKA This is directly related to a field that we are asking the user to fill in. In airtable it will be a single select of all 50 states. If we did locale, what would we use for the single select that isn't a state?

**Comment by HarryAKA** [comment]
i just worry about it being too prescriptive since not all resources will fall into a "state" category, some could be national/regional, or even international. i'd rather we give submitters the freedom to define the locale

**Comment by dforz** [comment]
@HarryAKA We want to bucket so that they can be organized into pages. You are correct it won't be as granular. Let's start with states and then we can adjust if needed. I can change the name on the input form if we add more options, but in the table, it will still show state. ¯\_(ツ)_/¯

**Comment by HarryAKA** [comment]
yeah i get that, just questioning if state is actually the best way to bucket by location. now our form has to include huge single select list that is only relevant to american users. i feel like a better approach would be freetext entry with typeahead suggestions for existing categories. not sure if airtable forms can do that out of the box though

**Pull request merged**
