### PR TITLE
Link Request: Cincinnati Relief Fund -> https://www.gofundme.com/f/cincinnati-relief-fund

### PR DESCRIPTION
**Pull request by wipeyadocsoff**
This is an automated pull request.

### CODE REVIEW

**Comment by illegalprime** [comment]
ah this is probably a bad format because netlify likely will read it as:
`/Cincinnati -> Relief`

**Comment by HarryAKA** [comment]
yeah this wont work, are we able to add field-level validation to the airtable form?

**Comment by wipeyadocsoff** [comment]
we could slugify names automatically

**Comment by illegalprime** [comment]
I think the requester should instead pick a slug that they would like to see, because ultimately this is supposed to shorted the link and make it easy to remember. And there are many way to do that.

**Comment by HarryAKA** [comment]
manually fixed slug, we're exploring ways to do this automatically going forward

**Pull request merged**
