### PR TITLE
Add /censor as a redirect to https://everestpipkin.github.io/image-scrubber/

### PR DESCRIPTION
**Pull request by monarrk**

### CODE REVIEW

**Comment by HarryAKA** [comment]
I'd prefer a more descriptive slug like, maybe just /image-scrubber/

**Comment by wipeyadocsoff** [comment]
maybe just /scrub ?

**Comment by HarryAKA** [comment]
i dig it

**Comment by monarrk** [comment]
/scrub would work too, /censor was just the first thing to pop into my head. I'll try to update tomorrow

**Comment by monarrk** [comment]
There we are!

**Pull request merged**
