### PR TITLE
add script to generate prs from airtable forms

### PR DESCRIPTION
**Pull request by illegalprime**
1. take rows from airtable without a github PR link attached
2. create a branch and commit data to it
3. make a pr from that branch
4. add github pr link to airtable to not recreate duplicate prs

we would need to run this somewhere with these two secrets: `AIRTABLE_API_KEY`, `GITHUB_API_KEY`

we should also turn on the setting that deletes branches once PRs are merged

### CODE REVIEW

**Comment by HarryAKA** [comment]
could you add another filter to the airtable select that excludes duplicate slugs from `_redirects` so the script can be more reusable?

**Comment by illegalprime** [comment]
I believe "no duplicates" are enforced in Airtable but @dforz implemented that part, so asking him to confirm.

**Comment by HarryAKA** [comment]
i mean if we ran the script multiple times (to pull newly added urls) it would generate pr's for rows that already exist in `_redirects`, right?

**Comment by dforz** [comment]
Good point @HarryAKA Unfortunately, there is no way to prevent duplicates in even the primary column in airtable. Perhaps we append something to the name to make it unique? 

Side note: We also want to handle the case where the url already exists.

**Comment by illegalprime** [comment]
I think preventing duplicates in the airtable is probably not what we want, since then only the _first_ person to request something gets a PR (because I don't think we're deleting rows).

I think if it just fails silently people will be confused why their request didn't go through.

What if we add `[DUPLICATE]` in the PR title for slugs already in the `_redirects` file?

**Comment by HarryAKA** [comment]
sorry if i wasn't clear, what i meant was the script needs to ignore slug/url pairs that already exist in `_redirects` otherwise it can only be ran once on the airtable without generating dupe PRs

**Comment by illegalprime** [comment]
@HarryAKA  do you think it's worthwhile adding `[DUPLICATE]` or just not make a pr at all?

**Comment by HarryAKA** [comment]
i think if the url is unique make a pr but if it's an existing url with new slug or existing slug/url pair ignore.

**Comment by illegalprime** [comment]
@wipeyadocsoff what do you think? I think it's valuable for people to be able to see feedback on why their submission was rejected, even if it's just because it's a duplicate. Better would be if we tell them as they're filling out their form.

**Comment by wipeyadocsoff** [comment]
i agree

**Pull request merged**
